name: spending_management

description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^20.2.44
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  fl_chart:
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: 's'
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  
# flutter packages pub run build_runner build
  
  
  
  
  
  
  
  
  
